const express=require('express');
const path=require('path');
const session=require('express-session');
const bcrypt=require('bcryptjs');
const {Pool}=require('pg');
const crypto=require('crypto');
const app=express();
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?{rejectUnauthorized:false}:undefined});
app.use(express.json());app.use(express.urlencoded({extended:true}));
app.use(session({secret:process.env.SESSION_SECRET||'change-me-production',resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:86400000}}));
app.use(express.static(path.join(__dirname,'public')));
const q=(t,p=[])=>pool.query(t,p);
async function init(){if(!process.env.DATABASE_URL){console.warn('DATABASE_URL missing');return;}await q(`CREATE TABLE IF NOT EXISTS admins(id SERIAL PRIMARY KEY,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,created_at TIMESTAMPTZ DEFAULT NOW());CREATE TABLE IF NOT EXISTS products(id SERIAL PRIMARY KEY,name TEXT NOT NULL,category TEXT NOT NULL,description TEXT DEFAULT '',price INTEGER NOT NULL,stock INTEGER NOT NULL DEFAULT 0,image_url TEXT DEFAULT '',active BOOLEAN DEFAULT TRUE,created_at TIMESTAMPTZ DEFAULT NOW());CREATE TABLE IF NOT EXISTS coupons(id SERIAL PRIMARY KEY,code TEXT UNIQUE NOT NULL,discount_percent INTEGER DEFAULT 0,active BOOLEAN DEFAULT TRUE,created_at TIMESTAMPTZ DEFAULT NOW());CREATE TABLE IF NOT EXISTS orders(id SERIAL PRIMARY KEY,order_no TEXT UNIQUE NOT NULL,customer_name TEXT NOT NULL,phone TEXT NOT NULL,email TEXT DEFAULT '',address TEXT NOT NULL,payment_method TEXT NOT NULL DEFAULT 'bank',payment_status TEXT NOT NULL DEFAULT 'pending',shipping_status TEXT NOT NULL DEFAULT 'pending',subtotal INTEGER NOT NULL,discount INTEGER NOT NULL DEFAULT 0,total INTEGER NOT NULL,coupon_code TEXT DEFAULT '',items JSONB NOT NULL,created_at TIMESTAMPTZ DEFAULT NOW());`);let a=await q('SELECT id FROM admins LIMIT 1');if(!a.rowCount){let h=await bcrypt.hash(process.env.ADMIN_PASSWORD||'ChangeMe123!',12);await q('INSERT INTO admins(email,password_hash) VALUES($1,$2)',[process.env.ADMIN_EMAIL||'admin@yu-yan.tw',h]);}let p=await q('SELECT id FROM products LIMIT 1');if(!p.rowCount){const seed=[['燕窩晶鑽禮盒','精品燕窩',3680,30],['梨山高山烏龍雙入禮盒','台灣高山茶',2680,40],['燕窩・高山茶臻選禮盒','養生禮盒',6280,25],['尊榮養生禮盒','尊榮系列',8800,20],['珍藏燕窩禮贈組','VIP系列',16800,12],['御燕尊榮典藏組','VIP典藏',39800,8]];for(const x of seed)await q('INSERT INTO products(name,category,price,stock,description) VALUES($1,$2,$3,$4,$5)',[x[0],x[1],x[2],x[3],'精緻包裝，適合自用與重要節慶送禮。']);}}}
function admin(req,res,next){if(req.session.admin)return next();res.status(401).json({error:'unauthorized'});}
app.get('/api/products',async(req,res)=>{try{res.json((await q('SELECT * FROM products WHERE active=true ORDER BY id')).rows)}catch(e){res.status(500).json({error:'database'})}});
app.post('/api/checkout',async(req,res)=>{try{const {customer,items,coupon,payment_method}=req.body;if(!customer?.name||!customer?.phone||!customer?.address||!Array.isArray(items)||!items.length)return res.status(400).json({error:'資料不完整'});const ids=items.map(x=>Number(x.id)).filter(Boolean);const pr=(await q('SELECT * FROM products WHERE id=ANY($1::int[]) AND active=true',[ids])).rows;let subtotal=0,out=[];for(const i of items){const p=pr.find(x=>x.id==i.id);const qty=Math.max(1,Math.min(20,Number(i.qty)||1));if(!p||p.stock<qty)return res.status(400).json({error:'商品庫存不足'});subtotal+=p.price*qty;out.push({id:p.id,name:p.name,price:p.price,qty});}let discount=0,code='';if(coupon){const c=(await q('SELECT * FROM coupons WHERE upper(code)=upper($1) AND active=true',[coupon])).rows[0];if(c){discount=Math.floor(subtotal*c.discount_percent/100);code=c.code;}}const total=subtotal-discount;const no='YY'+Date.now().toString().slice(-10)+crypto.randomInt(10,99);await q('BEGIN');try{for(const i of out)await q('UPDATE products SET stock=stock-$1 WHERE id=$2 AND stock >= $1',[i.qty,i.id]);await q('INSERT INTO orders(order_no,customer_name,phone,email,address,payment_method,subtotal,discount,total,coupon_code,items) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)',[no,customer.name,customer.phone,customer.email||'',customer.address,payment_method||'bank',subtotal,discount,total,code,JSON.stringify(out)]);await q('COMMIT')}catch(e){await q('ROLLBACK');throw e}res.json({ok:true,order_no:no,total,payment_status:'pending',message:'訂單已建立。正式信用卡需完成金流商家設定後啟用。'});}catch(e){console.error(e);res.status(500).json({error:'建立訂單失敗'})}});
app.get('/api/order/:no',async(req,res)=>{try{const r=await q('SELECT order_no,customer_name,payment_status,shipping_status,total,created_at FROM orders WHERE order_no=$1',[req.params.no]);if(!r.rowCount)return res.status(404).json({error:'找不到訂單'});res.json(r.rows[0])}catch(e){res.status(500).json({error:'database'})}});
app.post('/api/admin/login',async(req,res)=>{try{const a=(await q('SELECT * FROM admins WHERE email=$1',[req.body.email])).rows[0];if(!a||!await bcrypt.compare(req.body.password||'',a.password_hash))return res.status(401).json({error:'帳號或密碼錯誤'});req.session.admin={id:a.id,email:a.email};res.json({ok:true})}catch(e){res.status(500).json({error:'database'})}});
app.post('/api/admin/logout',(req,res)=>req.session.destroy(()=>res.json({ok:true})));
app.get('/api/admin/dashboard',admin,async(req,res)=>{const [o,p]=await Promise.all([q('SELECT COUNT(*)::int orders,COALESCE(SUM(total),0)::int revenue FROM orders'),q('SELECT COUNT(*)::int products,COALESCE(SUM(stock),0)::int stock FROM products')]);res.json({...o.rows[0],...p.rows[0]})});
app.get('/api/admin/orders',admin,async(req,res)=>res.json((await q('SELECT * FROM orders ORDER BY created_at DESC LIMIT 200')).rows));
app.patch('/api/admin/orders/:id',admin,async(req,res)=>{const {payment_status,shipping_status}=req.body;await q('UPDATE orders SET payment_status=COALESCE($1,payment_status),shipping_status=COALESCE($2,shipping_status) WHERE id=$3',[payment_status||null,shipping_status||null,req.params.id]);res.json({ok:true})});
app.get('/api/admin/products',admin,async(req,res)=>res.json((await q('SELECT * FROM products ORDER BY id')).rows));
app.post('/api/admin/products',admin,async(req,res)=>{const {name,category,description,price,stock,image_url}=req.body;const r=await q('INSERT INTO products(name,category,description,price,stock,image_url) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[name,category,description||'',Number(price),Number(stock),image_url||'']);res.json(r.rows[0])});
app.patch('/api/admin/products/:id',admin,async(req,res)=>{const {name,category,description,price,stock,image_url,active}=req.body;const r=await q('UPDATE products SET name=$1,category=$2,description=$3,price=$4,stock=$5,image_url=$6,active=$7 WHERE id=$8 RETURNING *',[name,category,description||'',Number(price),Number(stock),image_url||'',active!==false,req.params.id]);res.json(r.rows[0])});
app.get('/api/admin/coupons',admin,async(req,res)=>res.json((await q('SELECT * FROM coupons ORDER BY id DESC')).rows));
app.post('/api/admin/coupons',admin,async(req,res)=>{const r=await q('INSERT INTO coupons(code,discount_percent) VALUES(upper($1),$2) RETURNING *',[req.body.code,Number(req.body.discount_percent)]);res.json(r.rows[0])});
app.get('/admin',(req,res)=>res.sendFile(path.join(__dirname,'public','admin.html')));app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
const port=process.env.PORT||3000;init().then(()=>app.listen(port,'0.0.0.0',()=>console.log('Yu Yan Tea V2 on '+port))).catch(e=>{console.error(e);process.exit(1)});